services:
  php_apache_landingpagetailtype:
    build:
      context: .
      dockerfile: ./php_server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: php_apache_${PROJECT_NAME}
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_${PROJECT_NAME}

  mysql:
    image: mysql:latest
    container_name: mysql-${PROJECT_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent-${PROJECT_NAME}:/var/lib/mysql:rw
    depends_on:
      - php_apache_${PROJECT_NAME}
    networks:
      - network_${PROJECT_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${PROJECT_NAME}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_${PROJECT_NAME}

  phpunit:
    build:
      context: .
      dockerfile: ./php_server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    volumes:
      - .:/app
    networks:
      - network_${PROJECT_NAME}
    entrypoint: ["phpunit", "--configuration", "/app/phpunit.xml"]

networks:
  network_landingpagetailtype:
    name: network_${PROJECT_NAME}

volumes:
  persistent-landingpagetailtype:
